version: "3"

services:
  app-postgres:
    image: postgres
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - app-volume:/var/lib/postgresql/data
    networks:
      - app-backend

volumes:
  app-volume:

networks:
  app-backend:
